// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return the professional profile of Mohamed Mohamud SH Hassan: name, brand, title, summary, and areas of expertise.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Mohamed Mohamud SH Hassan",
      brand: "AgroPath",
      titles: [
        "Plant Pathology Specialist",
        "Seed Inspector",
        "Founder & CEO of PathoSolutions"
      ],
      tagline: "Advancing Sustainable Agriculture Through Science",
      summary: "Plant pathology specialist and seed inspector working at the intersection of research, regulation, and farmer support. Focus areas include seed quality assurance, plant disease diagnostics, integrated pest management, and climate-smart agriculture, with a mission aligned to UN SDG 2 (Zero Hunger) and African agricultural transformation.",
      expertise: [
        "Plant Pathology & Diagnostics",
        "Seed Inspection & Certification",
        "Integrated Pest Management (IPM)",
        "Climate-Smart Agriculture",
        "Agricultural Research & Extension"
      ],
      website: "https://agropath.lovable.app"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_experience_default = defineTool2({
  name: "get_experience",
  title: "Get professional experience",
  description: "Return the professional experience timeline for Mohamed Mohamud SH Hassan, including roles, organizations, dates, and key achievements.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const experience = [
      {
        title: "Seed Inspector",
        organization: "Somali Agricultural Regulatory and Inspection Services (SARIS)",
        period: "September 2025 \u2013 Present",
        current: true,
        achievements: [
          "Certified seed varieties for national distribution",
          "Ensured regulatory compliance with international phytosanitary standards",
          "Performed field and laboratory quality assessments for seed integrity",
          "Provided strategic advisory to the Ministry of Agriculture on seed policy"
        ]
      },
      {
        title: "Founder & CEO",
        organization: "PathoSolutions",
        period: "2024 \u2013 Present",
        current: true,
        achievements: [
          "Scaled agricultural innovation platform to 500+ farmers served",
          "Developed and managed an agricultural blog and knowledge platform",
          "Cultivated strategic partnerships with international organizations",
          "Promoted evidence-based plant disease management solutions"
        ]
      },
      {
        title: "Lecturer & Research Supervisor",
        organization: "Afgoye International University, Somalia",
        period: "April 2025 \u2013 September 2025",
        current: false,
        achievements: [
          "Mentored 2+ students in plant pathology and crop protection",
          "Supervised student research projects in sustainable agriculture",
          "Modernized curriculum to align with global agricultural standards",
          "Introduced evidence-based teaching methodologies"
        ]
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
      structuredContent: { experience }
    };
  }
});

// src/lib/mcp/tools/get-education.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_education_default = defineTool3({
  name: "get_education",
  title: "Get education and memberships",
  description: "Return academic credentials and professional memberships for Mohamed Mohamud SH Hassan.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = {
      education: [
        {
          degree: "MSc in Plant Pathology",
          institution: "Lovely Professional University (LPU), India"
        },
        {
          degree: "BSc in Agriculture",
          institution: "International University of Business Agriculture and Technology (IUBAT), Bangladesh"
        }
      ],
      memberships: [
        {
          organization: "FAO e-Agriculture Community",
          role: "Member",
          description: "Global community of practice on ICT for sustainable agriculture and rural development, hosted by the Food and Agriculture Organization of the United Nations."
        }
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "Get contact information",
  description: "Return public contact and social channels for Mohamed Mohamud SH Hassan, including email, phone, WhatsApp, and blog.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      email: "maameyare07@gmail.com",
      phone: "+252612330512",
      whatsapp: "+252612330512",
      blog: "https://pathosolutions.blogspot.com",
      website: "https://agropath.lovable.app",
      location: "Somalia",
      inquiryTypes: [
        "Research collaboration",
        "Consulting",
        "Speaking / training",
        "Media / press",
        "General inquiry"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "agropath-mcp",
  title: "AgroPath \u2014 Mohamed Mohamud SH Hassan",
  version: "0.1.0",
  instructions: "Public portfolio MCP server for Mohamed Mohamud SH Hassan (AgroPath), a plant pathology specialist and seed inspector. Use these tools to answer questions about his profile, professional experience, education and memberships, and public contact channels.",
  tools: [get_profile_default, get_experience_default, get_education_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
